language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
  - node_modules

before_install:
  - npm i -g npm
  - npm run install
  
install: true

script:
  - npm run lint

notifications:
  email:
    on_failure: change

after_success: 'npm run coveralls'
